# Generated by Django 5.1.3 on 2024-11-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_comment_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='picture',
            field=models.ImageField(upload_to='comment_pictures/'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='picture',
            field=models.ImageField(upload_to='news_pictures/'),
        ),
    ]
