# Generated by Django 5.1.3 on 2024-12-01 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_newsitem_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='NewsItem',
            new_name='news_item',
        ),
    ]
