# Generated by Django 5.1.3 on 2024-12-01 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_rename_newsitem_comment_news_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='news_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.newsitem'),
        ),
    ]
